name: Basic Tests

on:
  workflow_dispatch:

# permissions:
#   contents: read

permissions:
  contents: read

jobs:
  overwrite:
    if: always()
    runs-on: ARMLinuxRunner
    steps:
      - uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # rc
        with:
          egress-policy: audit
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: echo overwrite
        run: echo "## Overwritten" >> README.md

      - name: mv overwrite
        run: echo "# Replaced" >> README2.md; mv README2.md README.md

  egress-test:
    if: always()
    runs-on: ARMLinuxRunner
    steps:
      - uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # rc
        with:
          egress-policy: block
          disable-sudo: true
          allowed-endpoints: |
            www.google.com:443

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - run: curl https://www.google.com
      - run: curl https://microsoft.com

  disabled-telemetry:
    if: always()
    runs-on: ARMLinuxRunner
    steps:
      - uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # rc
        with:
          egress-policy: block
          disable-sudo: true
          disable-telemetry: true
          allowed-endpoints: |
            www.google.com:443

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - run: curl https://www.google.com
      - run: curl https://microsoft.com
      - run: curl https://youtube.com
      - run: curl https://bing.com
