name: Docker Image CI

on:
  workflow_dispatch:
    

permissions: {}

jobs:

  build:
    permissions:
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    #runs-on: [self-hosted, ec2]
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@17d38b322b06d1108e77a84fb02658a27c4a7eb0 # rc
      with:
        egress-policy: audit
        allowed-endpoints: >
          auth.docker.io:443
          database.clamav.net:443
          current.cvd.clamav.net:443
          files.pythonhosted.org:443
          github.com:443
          production.cloudflare.docker.com:443
          pypi.org:443
          registry-1.docker.io:443

    - uses: actions/checkout@v2
          
    - name: Build the Docker image
      run: docker build . --file Dockerfile
