name: Docker Image CI

on:
  workflow_dispatch:
    

permissions: {}

jobs:

  build:
    permissions:
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    #runs-on: [self-hosted, ec2]
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # rc
      with:
        egress-policy: audit
        allowed-endpoints: >
          auth.docker.io:443
          database.clamav.net:443
          current.cvd.clamav.net:443
          files.pythonhosted.org:443
          github.com:443
          production.cloudflare.docker.com:443
          pypi.org:443
          registry-1.docker.io:443

    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
          
    - name: Build the Docker image
      run: docker build . --file Dockerfile
