name: Disabled Telemetry ARM

on:
  workflow_dispatch:

# permissions:
#   contents: read

permissions: {}

jobs:
  disabled-telemetry:
    permissions:
      contents: read  # for actions/checkout to fetch code
    if: always()
    runs-on: ARMLinuxRunner
    steps:
      - uses: step-security/harden-runner@17d38b322b06d1108e77a84fb02658a27c4a7eb0 # rc
        with:
          egress-policy: block
          disable-sudo: true
          disable-telemetry: true
          allowed-endpoints: |
            www.google.com:443

      - uses: actions/checkout@v3

      - run: curl https://www.google.com
      - run: curl https://microsoft.com
      - run: curl https://youtube.com
      - run: curl https://bing.com
