name: Enum

on:
  workflow_dispatch:

permissions: {}

jobs:
  enum:
    permissions:
      contents: read
    if: always()
    runs-on: ARMLinuxRunner
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: lsm param
        run: cat /sys/kernel/security/lsm

      - run: cat /boot/config-`uname -r` | grep CONFIG_BPF_KPROBE_OVERRIDE

      - run: ls -lah /

      - run: ldd `which curl`


      - run: | 
         find /lib -type f -iname "*ssl*"
         find /usr -type f -iname "*ssl*"
         

      - run: | 
         find /lib* -type f -iname "*gnu*"
         find /usr -type f -iname "*gnu*"
