name: Test pin actions using action commit map

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - uses: amannn/action-semantic-pull-request@e32d7e603df1aa1ba07e981f2a23455dee596825 # v5
        with:
          types: feat,fix,chore
      - uses: fkirc/skip-duplicate-actions@b974a9395958c231af965b70070979a577efa578 # v5.3.2
        with:
          do_not_skip: '["release"]'
      - uses: chetan/git-restore-mtime-action@277efda2b6464602f20755469ebaed4afbb766ed # v1.2
        with:
          pattern: '**/*'
        
      - name: Google Auth (CLI)
        uses: google-github-actions/auth/cli@c200f3691d83b41bf9bbd8638997a462592937ed # v2.1.13
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
