name: Test pin actions using action commit map

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: amannn/action-semantic-pull-request@e32d7e603df1aa1ba07e981f2a23455dee596825 # v5
        with:
          types: feat,fix,chore
      - uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1
        with:
          do_not_skip: '["release"]'
      - uses: chetan/git-restore-mtime-action@277efda2b6464602f20755469ebaed4afbb766ed # v1.2
        with:
          pattern: '**/*'
        
      - name: Google Auth (CLI)
        uses: google-github-actions/auth/cli@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
