name: Label Added Trigger

on:
  issues:
    types:
      - labeled
  pull_request:
    types:
      - labeled

permissions:
  contents: read

jobs:
  label-check-job:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Curl to google.com
        run: curl -v https://www.google.com
