name: Policy Store - Repo Level

on: 
  workflow_dispatch:
    inputs:
      ami-id:
        description: 'AMI ID to use for the runners'
        required: true

permissions: {}

jobs:
  repo-level-policy:
    permissions:
      contents: read  # for actions/checkout to fetch code
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=2cpu-linux-x64
      - ami=${{ inputs.ami-id }}

    steps:
      # - name: Harden the runner
      #   uses: step-security/harden-runner@feature/policy-store
      #   with:
      #     use-policy-store: true
      #     api-key: ${{ secrets.STEP_SECURITY_API_KEY }}
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: call google
        run: |
          curl https://google.com

      - name: call bing
        run: |
          curl https://bing.com

      - name: call microsoft
        run: |
          curl https://microsoft.com

      - name: call amazon
        run: |
          curl https://amazon.com
