name: Test Fail with Compromised Action

on:
  workflow_dispatch:

permissions: {}

jobs:
  test-fail:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: sleep
        run: |
          echo "Sleep 5"
          sleep 5


      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Use compromised action (should be blocked)
        uses: step-security/dummy-compromised-action@c96c327cecdb71e8f031080ba8ad208feb25b13d # v1
        
      - name: sleep
        if: always()
        run: |
          echo "Sleep 5"
          sleep 5

      - name: Display results
        run: |
          echo "Workflow completed successfully"
          echo "This is a fail scenario for workflow run policies"
