name: azure/setup-kubectl
on:
  workflow_dispatch:
  
permissions: {}

jobs:
  generate-jobs:
    permissions:
      contents: read
    name: Generate Jobs
    runs-on: ubuntu-latest
   
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - uses: azure/setup-kubectl@0c5e050edfed71b2b50731ab044d42489d51c129 # vv4.0.0
      - run: sleep 300
        
           
