name: TLS Basic Tests

on:
  workflow_dispatch:

# permissions:
#   contents: read

permissions:
  contents: read

jobs:
  dynamic-node:
    if: always()
    runs-on: ARMLinuxRunner
    steps:
      - uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # rc
        with:
          egress-policy: audit
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - run: which node
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "16"

      - run: which node

      - run: node req.js

  owner-mismatch:
    if: always()
    runs-on: ARMLinuxRunner
    steps:
      - uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # rc
        with:
          egress-policy: audit
      - run: curl -XPOST https://api.github.com/repos/malicious-owner/malicious-repo
