name: TLS Basic Tests

on:
  workflow_dispatch:

# permissions:
#   contents: read

permissions: {}

jobs:
  dynamic-node:
    permissions:
      contents: read  # for actions/checkout to fetch code
    if: always()
    runs-on: ARMLinuxRunner
    steps:
      - uses: step-security/harden-runner@17d38b322b06d1108e77a84fb02658a27c4a7eb0 # rc
        with:
          egress-policy: audit
      - uses: actions/checkout@v3
      - run: which node
      - uses: actions/setup-node@v4
        with:
          node-version: "16"

      - run: which node

      - run: node req.js

  owner-mismatch:
    permissions:
      contents: read  # for actions/checkout to fetch code
    if: always()
    runs-on: ARMLinuxRunner
    steps:
      - uses: step-security/harden-runner@17d38b322b06d1108e77a84fb02658a27c4a7eb0 # rc
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@v4
      - run: curl -XPOST https://api.github.com/repos/malicious-owner/malicious-repo
