name: TLS Basic Tests

on:
  workflow_dispatch:

# permissions:
#   contents: read

jobs:
  dynamic-node:
    if: always()
    runs-on: ARMLinuxRunner
    steps:
      - uses: step-security/harden-runner@rc
        with:
          egress-policy: audit
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - run: which node
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "16"

      - run: which node

      - run: node req.js

  owner-mismatch:
    if: always()
    runs-on: ARMLinuxRunner
    steps:
      - uses: step-security/harden-runner@rc
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - run: curl -XPOST https://api.github.com/repos/malicious-owner/malicious-repo
