name: TLS Github API Calls

on:
  workflow_dispatch:

# permissions:
#   contents: read

permissions: {}

jobs:
  issue-create:
    permissions:
      contents: write
      issues: write
    if: always()
    runs-on: ARMLinuxRunner
    steps:
      - run: free -m

      - uses: step-security/harden-runner@rc
        with:
          egress-policy: audit
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: free -m

  create-pr:
    permissions:
      contents: write
      pull-requests: write
    if: always()
    runs-on: ARMLinuxRunner
    steps:
      - run: free -m
      - uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - run: "echo '// changes' >> main.js"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: free -m

  comment-on-pr:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6 # v2.5.0
        with:
          message: |
            Hello world ! :wave:
          pr_number: 1

  dispatch-workflow:
    permissions:
      contents: write
      actions: write
    if: always()
    runs-on: ARMLinuxRunner
    steps:
      - run: free -m
      - uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@31e2b3319479a63f0ab15bf800eff9e913504e26 # v1.3.2
        with:
          workflow: enumeration.yml
      - run: free -m
